### PR TITLE
VLC Android

### PR DESCRIPTION
**Pull request by MiroValchev**
Guys, I have implemented VLC player for Android. It should be faster, have more options and be more robust than the native player. Done in collaboration with @Ivshti.

I hope it might help someone else. @bradmartin Let me know what you think - does it make sense to merge it in the master or it should remain as a separate fork?

### CODE REVIEW

**Comment by bradmartin** [comment]
Hey @MiroValchev good work! As for merging, I don't think this is something we would add to this plugin. This plugin is currently being verified by the NativeScript team to be listed as a 'Verified' plugin on their site.

Also, since this is just the Android side it would add some bloat to the Android side. Do you have an idea of the added file size to the .apk with VLC? Let's continue to discuss this later on I have a meeting now. :+1:

**Comment by Ivshti** [comment]
@bradmartin unfortunately vlc does add something like 50-60 mb to the apk size.

And I am also inclined to think that this plugin should use the native player by default, but I think either a vlc option or a twin-fork (same API) is a good idea

**Comment by bradmartin** [comment]
You could always publish a vlc player plugin if you wanted to maintain it :)

**Comment by bradmartin** [comment]
Yea that much added 50-60mb is a bit heavy for this. I think you should publish a vlc player plugin yourself but I'd make note of the added package size so devs know up front what they're getting. :)

**Comment by MiroValchev** [comment]
@bradmartin I think you are right. We will publish this a a separate plugin. The video plugin should stay light.

**Pull request closed without merging**
